services:
  stomp-server:
    build:
      context: ./server
    container_name: stomp-server
    ports:
      - "${PORT:-7777}:${PORT:-7777}"
    environment:
      PORT: ${PORT:-7777}
      SERVER_TYPE: ${SERVER_TYPE:-reactor}
    networks:
      - stomp-network

  stomp-client:
    build:
      context: ./client
    container_name: stomp-client
    networks:
      - stomp-network

networks:
  stomp-network:
    driver: bridge
